#!/usr/bin/env bash
# installs, configures and starts nginx server

sudo apt update -y
sudo apt install nginx -y


sudo ufw allow 'Nginx HTTP'

echo Hello World! > /var/www/html/index.nginx-debian.html

sudo service start nginx
