#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another 
# page.

sudo apt update -y
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'

echo Hello World! > /var/www/html/index.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}

	if (\$request_filename ~ redirect_me){
		rewrite ^ https://sketchfab.com/bluepeno/models permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi