#!/usr/bin/env bash
# install and configure HAproxy on lb-o1 server

sudo apt -y update
sudo apt -y upgrade
sudo apt install -y haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 59637-web-01 54.160.85.72:80 check
    server 59637-web-02 35.175.132.106:80 check
" > /etc/haproxy/haproxy.cfg
sudo service haproxy start