#!/usr/bin/env bash
# This script loops from 1 t0 10
#   displays 'bad luck' on the 4th iteration
#   displays 'good luck' on the 8th iteration
#   displays 'Best School' on the every other iteration
i=1

while [ $i -le 10 ]
do
    if [[ $i -eq 4 ]]
    then
        echo "bad luck"
    elif [[ $i -eq 8 ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
    